# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  demands: 
    2020.3.23f1

steps:
# - task: UnityBuildTask@3
#   inputs:
#     buildTarget: 'Win64'
#     unityProjectPath: 'D:\unity_project\firstGame-master\New Unity Project'
#     outputPath: '$(Build.BinariesDirectory)\builds'
#     outputFileName: 'Simple'
- task: UnityBuildTask@3
  inputs:
    buildTarget: 'Android'
    unityProjectPath: 'D:\unity_project\firstGame-master\New Unity Project'
    outputPath: '$(Build.BinariesDirectory)\builds'
    outputFileName: 'Simple'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.BinariesDirectory)\builds'
    artifact: 'build$(Build.Number)'
    publishLocation: 'pipeline'
# - task: AzureFileCopy@4
#   inputs:
#     azureSubscription: 'Azure subscription 1(9d46a63b-0469-40f9-a066-8e537f2d6aff)'
#     Destination: 'AzureBlob'
#     storage: 'unitybuildhub'
#     ContainerName: '
- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(Build.BinariesDirectory)\builds'
    azureSubscription: 'Azure subscription 1(9d46a63b-0469-40f9-a066-8e537f2d6aff)'
    Destination: 'AzureBlob'
    storage: 'unitybuildhub'
    ContainerName: 'Game_builds_android'
