# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  demands: 
    2020.3.23f1

steps:
- task: UnityBuildTask@3
  inputs:
    buildTarget: 'Win64'
    unityProjectPath: 'D:\unity_project\firstGame-master\New Unity Project'
    outputPath: '$(Build.BinariesDirectory)\builds'
    outputFileName: 'Simple'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.BinariesDirectory)\builds'
    artifact: 'build$(Build.Number)'
    publishLocation: 'pipeline'